identify_key_questions_task:
  description: >
    Identify the critical questions that need to be addressed to thoroughly understand 
    and evaluate the topic of **{topic}**. Focus on foundational principles, significant challenges, 
    and areas that require further research or exploration to build a strong basis for discussion.
  expected_output: >
    - A Markdown bullet list of essential and thought-provoking questions about **{topic}**.
  async_execution: true

analyze_potential_impacts_task:
  description: >
    Conduct an analysis of the potential impacts of **{topic}** across economic, social, and 
    political dimensions. Include both positive and negative consequences, ensuring a balanced view. 
    Clearly outline key needs, concerns, and expectations to provide actionable insights.
  expected_output: >
    - A Markdown bullet list of key points exploring the potential impacts of **{topic}**, categorized 
      into positive and negative outcomes where applicable.
  async_execution: true

propose_possible_solutions_task:
  description: >
    Develop and propose actionable solutions or strategies to address the questions 
    and challenges identified for **{topic}**. Ensure the solutions are realistic and 
    consider multiple perspectives. Provide at least three well-defined proposals.
  expected_output: >
    - A Markdown bullet list of at least three actionable solutions to the challenges related to **{topic}**.
    All of them should be detailed and feasible, considering the potential impacts and implications.
  async_execution: true

evaluate_feasibility_task:
  description: >
    Assess the practicality and feasibility of the proposed solutions for **{topic}**. 
    Evaluate resource requirements, potential barriers, and the overall viability of each solution. 
    For each idea, provide a detailed breakdown of its strengths and weaknesses, emphasizing its 
    suitability for implementation.
  expected_output: >
    - A Markdown enumeration summarizing the advantages and disadvantages of each proposed solution.
  async_execution: true

reporting_task:
  description: >
    Consolidate the outputs of all preceding tasks into a comprehensive Markdown report. 
    The report should highlight the key questions, discussions, and recommended actions, 
    and provide a clear summary of the contributions made by each agent ({agents}). 
    Ensure the report captures a holistic view of the consensus-building process and final findings.
  expected_output: >
    - A Markdown document summarizing the entire process, emphasizing:
      - Key questions and their origins.
      - Contributions, ideas, and concerns raised by each agent.
      - Final proposed solutions and their feasibility assessments.


formulate_proposal_task:
  description: >
    As the judge, your task is to formulate a proposal that integrates the most critical needs 
    and expectations of all stakeholders related to **{topic}**. Review the summary of key 
    questions, discussions, and recommended actions from the previous tasks ({result}). 
    Carefully analyze the diverse ideas and perspectives to create a cohesive solution that 
    balances inclusivity and feasibility. 
    Consider:
      - How can elements of different ideas be woven together to address key needs?
      - Are there compromises or trade-offs required to meet the expectations of all stakeholders?
      - How will the proposal address the most pressing challenges or concerns?
    Provide a clear and justified proposal that stakeholders can evaluate and amend.
  expected_output: >
    - A Markdown document containing:
      - The final proposed solution for **{topic}**.
      - Justification for each element of the proposal, explaining how it addresses key needs and challenges.


amend_proposal_task:
  description: >
    Your task is to individually review the proposal generated by the judge and suggest improvements. 
    Focus on areas where the proposal could be refined to better meet the needs of all stakeholders. 
    Consider:
      - Are there elements that need further clarification or development?
      - Are there any gaps, oversights, or unintended consequences in the proposal?
      - Can the proposal be made more practical, inclusive, or resource-efficient?
    Suggest specific changes and provide detailed justifications for each proposed amendment. 
    Be constructive and precise in your feedback to help refine the proposal.
  expected_output: >
    - A Markdown document detailing:
      - Suggested changes to the proposal.
      - Justifications for each suggested change, referencing specific areas of improvement 
        (e.g., practicality, inclusivity, resource allocation, etc.).
  async_execution: true

integrate_amends_task:
  description: >
    As the judge, your task is to integrate the suggested amendments from all agents into the original 
    proposal. Carefully evaluate each suggestion to determine its feasibility and relevance, and ensure 
    that the revised proposal addresses the identified areas of enhancement without losing coherence. 
    Consider:
      - Which amendments enhance the proposal's effectiveness or inclusivity without creating new challenges?
      - Are there any conflicting amendments, and if so, how can they be reconciled?
      - Does the revised proposal remain practical and aligned with stakeholder needs?
    Your final output should be a clear, refined proposal that balances all perspectives while addressing 
    key improvements.
  expected_output: >
    - A Markdown document containing the revised proposal for **{topic}**.



collect_agent_responses_task:
  description: >
    You are tasked with evaluating the proposal. Consider its implications carefully and individually 
    decide your stance. Indicate whether you:
      - Block: Strongly oppose and believe the proposal cannot move forward as is.
      - Stand Aside: Remain neutral but do not support or block the proposal.
      - Have Reservations: Support the proposal with some concerns or hesitations.
      - Support: Fully agree with the proposal and believe it should move forward.
    Assign an importance score from 1 to 10 to reflect how critical your stance is to you. 
    Provide a clear and detailed explanation for your decision, ensuring your reasoning is grounded 
    in evidence or logical considerations. Your input is crucial for the consensus process.
    Base your answers on:
    {result}
  expected_output: >
    {
      "agent_id": "Identifier of the agent",
      "stance": "block/stand_aside/reservation/support",
      "importance": "Integer between 1 and 10",
      "reason": "Detailed explanation for your stance"
    }
  async_execution: true


recopilate_and_evaluate_task:
  description: >
    As the judge, your task is to gather and evaluate all responses collected from the agents. 
    Review the individual stances (block, stand aside, reservations, or support) and the importance 
    scores assigned by each agent. Synthesize this information to analyze the overall stance of the group. 
    Consider the following:
      - Identify trends or patterns in the stances (e.g., majority opinions, critical dissenting views).
      - Evaluate the reasoning provided by each agent and the importance scores assigned to their stance.
      - Weigh the collective feedback objectively, ensuring no individual agent's opinion unfairly dominates.
    Based on this analysis, decide whether the proposal should be accepted or rejected. Provide a 
    justification summarizing all opinions, balancing logical reasoning, importance scores, and feasibility.
  expected_output: >
    {
      "final_decision": {
        "accept_proposal": "true/false",
        "justification": "Detailed summary of all opinions and reasoning for the final decision"
      },
      "summary": {
        "blocks": [
          {
            "agent_id": "Identifier of the agent",
            "importance": "Importance score assigned by the agent",
            "reason": "Reason for blocking"
          }
        ],
        "stand_asides": [
          {
            "agent_id": "Identifier of the agent",
            "importance": "Importance score assigned by the agent",
            "reason": "Reason for standing aside"
          }
        ],
        "reservations": [
          {
            "agent_id": "Identifier of the agent",
            "importance": "Importance score assigned by the agent",
            "reason": "Reason for their reservation"
          }
        ],
        "supports": [
          {
            "agent_id": "Identifier of the agent",
            "importance": "Importance score assigned by the agent",
            "reason": "Reason for supporting"
          }
        ]
      }
    }
plan_action_task:
  description: >
    Outline what needs to happen next to implement the proposal. Specify the actions, 
    timelines, and responsible parties for execution. Be clear and detailed in your plan.
    Base your answers on:
    {result}
  expected_output: >
    - A Markdown list detailing:
      - Actions required to implement the proposal.
      - Deadlines for each action.
      - Responsible individuals or groups for each task.
  async_execution: true

generate_consensus_report_task:
  description: >
    Produce a detailed Markdown report summarizing the contributions of each agent 
    to the different parts of the consensus process, the final proposal, and the action plan.
  expected_output: >
    You should provide a Markdown document, below you have a sketch of the structure:
    # Consensus-Building Report on **{topic}**
    
    ## Contributions of Each Agent
    - **Agent 1**:
      - Blocks: [Details]
      - Reservations: [Details]
      - Supports: [Details]
      - Amendments: [Details]
      - Action Plan Contributions: [Details]
    - **Agent 2**:
      - ...
    
    ## Final Proposal
    - **Proposal**: Final integrated proposal text
    - **Justification**: Key reasons for this proposal and its elements
    
    ## Action Plan
    - **Action 1**: [Description of action]
      - **Deadline**: [By when]
      - **Responsible**: [Who is responsible]
    - **Action 2**: [Description of action]
      - ...
    
    ## Conclusion
    - Summary of the key decisions, contributions, and final agreements.

